export const countriesData = [
  {
    id: 1,
    name: "United States",
    capital: "Washington, D.C.",
    population: 331900000,
    continent: "North America",
    region: "Northern America",
    flag: "🇺🇸",
    majorCities: ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix"],
    landmarks: ["Statue of Liberty", "Grand Canyon", "Golden Gate Bridge", "Mount Rushmore", "Times Square"],
    neighbors: ["Canada", "Mexico"],
    languages: ["English"],
    currency: "US Dollar (USD)",
    area: 9833520,
    landlocked: false,
    independenceYear: 1776,
    unescoSites: ["Statue of Liberty", "Grand Canyon", "Independence Hall"],
    famousExports: ["Technology", "Aircraft", "Automobiles", "Pharmaceuticals"],
    shape: "north-america-large"
  },
  {
    id: 2,
    name: "Canada",
    capital: "Ottawa",
    population: 38000000,
    continent: "North America",
    region: "Northern America",
    flag: "🇨🇦",
    majorCities: ["Toronto", "Montreal", "Vancouver", "Calgary", "Edmonton"],
    landmarks: ["CN Tower", "Niagara Falls", "Rocky Mountains", "Parliament Hill"],
    neighbors: ["United States"],
    languages: ["English", "French"],
    currency: "Canadian Dollar (CAD)",
    area: 9984670,
    landlocked: false,
    independenceYear: 1867,
    unescoSites: ["Canadian Rocky Mountain Parks", "Old Quebec"],
    famousExports: ["Oil", "Lumber", "Maple Syrup", "Natural Gas"],
    shape: "canada"
  },
  {
    id: 3,
    name: "Mexico",
    capital: "Mexico City",
    population: 128900000,
    continent: "North America",
    region: "Central America",
    flag: "🇲🇽",
    majorCities: ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana"],
    landmarks: ["Chichen Itza", "Teotihuacan", "Cancun Beaches", "Copper Canyon"],
    neighbors: ["United States", "Guatemala", "Belize"],
    languages: ["Spanish"],
    currency: "Mexican Peso (MXN)",
    area: 1964375,
    landlocked: false,
    independenceYear: 1810,
    unescoSites: ["Chichen Itza", "Historic Centre of Mexico City"],
    famousExports: ["Automobiles", "Electronics", "Oil", "Silver"],
    shape: "mexico"
  },
  {
    id: 4,
    name: "Brazil",
    capital: "Brasília",
    population: 212600000,
    continent: "South America",
    region: "South America",
    flag: "🇧🇷",
    majorCities: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Fortaleza"],
    landmarks: ["Christ the Redeemer", "Sugarloaf Mountain", "Amazon Rainforest", "Iguazu Falls"],
    neighbors: ["Argentina", "Bolivia", "Colombia", "French Guiana", "Guyana", "Paraguay", "Peru", "Suriname", "Uruguay", "Venezuela"],
    languages: ["Portuguese"],
    currency: "Brazilian Real (BRL)",
    area: 8515767,
    landlocked: false,
    independenceYear: 1822,
    unescoSites: ["Brasília", "Historic Centre of Salvador de Bahia"],
    famousExports: ["Coffee", "Soybeans", "Iron Ore", "Aircraft"],
    shape: "brazil"
  },
  {
    id: 5,
    name: "Argentina",
    capital: "Buenos Aires",
    population: 45200000,
    continent: "South America",
    region: "South America",
    flag: "🇦🇷",
    majorCities: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "La Plata"],
    landmarks: ["Iguazu Falls", "Perito Moreno Glacier", "Andes Mountains", "Teatro Colón"],
    neighbors: ["Bolivia", "Brazil", "Chile", "Paraguay", "Uruguay"],
    languages: ["Spanish"],
    currency: "Argentine Peso (ARS)",
    area: 2780400,
    landlocked: false,
    independenceYear: 1816,
    unescoSites: ["Iguazu National Park", "Los Glaciares National Park"],
    famousExports: ["Beef", "Wine", "Soybeans", "Wheat"],
    shape: "argentina"
  },
  {
    id: 6,
    name: "United Kingdom",
    capital: "London",
    population: 67900000,
    continent: "Europe",
    region: "Western Europe",
    flag: "🇬🇧",
    majorCities: ["London", "Birmingham", "Manchester", "Glasgow", "Liverpool"],
    landmarks: ["Big Ben", "Tower of London", "Stonehenge", "Buckingham Palace", "Edinburgh Castle"],
    neighbors: ["Ireland"],
    languages: ["English"],
    currency: "Pound Sterling (GBP)",
    area: 242495,
    landlocked: false,
    independenceYear: null,
    unescoSites: ["Stonehenge", "Tower of London", "City of Bath"],
    famousExports: ["Financial Services", "Pharmaceuticals", "Automobiles", "Whisky"],
    shape: "uk"
  },
  {
    id: 7,
    name: "France",
    capital: "Paris",
    population: 65300000,
    continent: "Europe",
    region: "Western Europe",
    flag: "🇫🇷",
    majorCities: ["Paris", "Marseille", "Lyon", "Toulouse", "Nice"],
    landmarks: ["Eiffel Tower", "Louvre Museum", "Notre-Dame", "Arc de Triomphe", "Mont Saint-Michel"],
    neighbors: ["Spain", "Belgium", "Luxembourg", "Germany", "Switzerland", "Italy", "Monaco", "Andorra"],
    languages: ["French"],
    currency: "Euro (EUR)",
    area: 643801,
    landlocked: false,
    independenceYear: null,
    unescoSites: ["Palace of Versailles", "Mont-Saint-Michel", "Cathedral of Notre-Dame"],
    famousExports: ["Wine", "Cheese", "Aircraft", "Luxury Goods"],
    shape: "france"
  },
  {
    id: 8,
    name: "Germany",
    capital: "Berlin",
    population: 83200000,
    continent: "Europe",
    region: "Western Europe",
    flag: "🇩🇪",
    majorCities: ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt"],
    landmarks: ["Brandenburg Gate", "Neuschwanstein Castle", "Berlin Wall", "Cologne Cathedral"],
    neighbors: ["Denmark", "Poland", "Czech Republic", "Austria", "Switzerland", "France", "Luxembourg", "Belgium", "Netherlands"],
    languages: ["German"],
    currency: "Euro (EUR)",
    area: 357114,
    landlocked: false,
    independenceYear: null,
    unescoSites: ["Cologne Cathedral", "Castles of Augustusburg"],
    famousExports: ["Automobiles", "Machinery", "Chemicals", "Beer"],
    shape: "germany"
  },
  {
    id: 9,
    name: "Italy",
    capital: "Rome",
    population: 60400000,
    continent: "Europe",
    region: "Southern Europe",
    flag: "🇮🇹",
    majorCities: ["Rome", "Milan", "Naples", "Turin", "Florence"],
    landmarks: ["Colosseum", "Leaning Tower of Pisa", "Venice Canals", "Vatican City", "Trevi Fountain"],
    neighbors: ["France", "Switzerland", "Austria", "Slovenia", "San Marino", "Vatican City"],
    languages: ["Italian"],
    currency: "Euro (EUR)",
    area: 301340,
    landlocked: false,
    independenceYear: 1861,
    unescoSites: ["Historic Centre of Rome", "Venice and its Lagoon", "Historic Centre of Florence"],
    famousExports: ["Wine", "Fashion", "Automobiles", "Machinery"],
    shape: "italy"
  },
  {
    id: 10,
    name: "Spain",
    capital: "Madrid",
    population: 47400000,
    continent: "Europe",
    region: "Southern Europe",
    flag: "🇪🇸",
    majorCities: ["Madrid", "Barcelona", "Valencia", "Seville", "Bilbao"],
    landmarks: ["Sagrada Familia", "Alhambra", "Park Güell", "Prado Museum", "Plaza Mayor"],
    neighbors: ["Portugal", "France", "Andorra", "Morocco"],
    languages: ["Spanish", "Catalan", "Basque", "Galician"],
    currency: "Euro (EUR)",
    area: 505992,
    landlocked: false,
    independenceYear: null,
    unescoSites: ["Alhambra", "Works of Antoni Gaudí", "Historic City of Toledo"],
    famousExports: ["Wine", "Olive Oil", "Automobiles", "Pharmaceuticals"],
    shape: "spain"
  },
  {
    id: 11,
    name: "China",
    capital: "Beijing",
    population: 1439300000,
    continent: "Asia",
    region: "Eastern Asia",
    flag: "🇨🇳",
    majorCities: ["Shanghai", "Beijing", "Guangzhou", "Shenzhen", "Chongqing"],
    landmarks: ["Great Wall of China", "Forbidden City", "Terracotta Army", "Temple of Heaven", "Yangtze River"],
    neighbors: ["Russia", "Mongolia", "North Korea", "Vietnam", "Laos", "Myanmar", "India", "Bhutan", "Nepal", "Pakistan", "Afghanistan", "Tajikistan", "Kyrgyzstan", "Kazakhstan"],
    languages: ["Mandarin Chinese"],
    currency: "Yuan (CNY)",
    area: 9596961,
    landlocked: false,
    independenceYear: null,
    unescoSites: ["Great Wall of China", "Forbidden City", "Mausoleum of the First Qin Emperor"],
    famousExports: ["Electronics", "Machinery", "Textiles", "Toys"],
    shape: "china"
  },
  {
    id: 12,
    name: "Japan",
    capital: "Tokyo",
    population: 126500000,
    continent: "Asia",
    region: "Eastern Asia",
    flag: "🇯🇵",
    majorCities: ["Tokyo", "Osaka", "Yokohama", "Nagoya", "Kyoto"],
    landmarks: ["Mount Fuji", "Tokyo Tower", "Hiroshima Peace Memorial", "Fushimi Inari Shrine", "Himeji Castle"],
    neighbors: [],
    languages: ["Japanese"],
    currency: "Yen (JPY)",
    area: 377975,
    landlocked: false,
    independenceYear: null,
    unescoSites: ["Mount Fuji", "Historic Monuments of Ancient Kyoto", "Hiroshima Peace Memorial"],
    famousExports: ["Automobiles", "Electronics", "Machinery", "Robotics"],
    shape: "japan"
  },
  {
    id: 13,
    name: "India",
    capital: "New Delhi",
    population: 1380000000,
    continent: "Asia",
    region: "Southern Asia",
    flag: "🇮🇳",
    majorCities: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai"],
    landmarks: ["Taj Mahal", "Red Fort", "Gateway of India", "Qutub Minar", "Golden Temple"],
    neighbors: ["Pakistan", "China", "Nepal", "Bhutan", "Bangladesh", "Myanmar"],
    languages: ["Hindi", "English", "Bengali", "Telugu", "Marathi"],
    currency: "Indian Rupee (INR)",
    area: 3287263,
    landlocked: false,
    independenceYear: 1947,
    unescoSites: ["Taj Mahal", "Red Fort Complex", "Qutb Minar"],
    famousExports: ["Software Services", "Textiles", "Pharmaceuticals", "Jewelry"],
    shape: "india"
  },
  {
    id: 14,
    name: "Australia",
    capital: "Canberra",
    population: 25700000,
    continent: "Oceania",
    region: "Australia and New Zealand",
    flag: "🇦🇺",
    majorCities: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
    landmarks: ["Sydney Opera House", "Great Barrier Reef", "Uluru", "Harbour Bridge", "Twelve Apostles"],
    neighbors: [],
    languages: ["English"],
    currency: "Australian Dollar (AUD)",
    area: 7692024,
    landlocked: false,
    independenceYear: 1901,
    unescoSites: ["Great Barrier Reef", "Sydney Opera House", "Uluru-Kata Tjuta National Park"],
    famousExports: ["Iron Ore", "Coal", "Gold", "Natural Gas"],
    shape: "australia"
  },
  {
    id: 15,
    name: "Russia",
    capital: "Moscow",
    population: 145900000,
    continent: "Europe",
    region: "Eastern Europe",
    flag: "🇷🇺",
    majorCities: ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan"],
    landmarks: ["Red Square", "Kremlin", "Saint Basil's Cathedral", "Hermitage Museum", "Lake Baikal"],
    neighbors: ["Norway", "Finland", "Estonia", "Latvia", "Lithuania", "Poland", "Belarus", "Ukraine", "Georgia", "Azerbaijan", "Kazakhstan", "China", "Mongolia", "North Korea"],
    languages: ["Russian"],
    currency: "Russian Ruble (RUB)",
    area: 17098242,
    landlocked: false,
    independenceYear: 1991,
    unescoSites: ["Kremlin and Red Square", "Historic Centre of Saint Petersburg", "Lake Baikal"],
    famousExports: ["Oil", "Natural Gas", "Metals", "Weapons"],
    shape: "russia"
  },
  {
    id: 16,
    name: "South Africa",
    capital: "Pretoria",
    population: 59300000,
    continent: "Africa",
    region: "Southern Africa",
    flag: "🇿🇦",
    majorCities: ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth"],
    landmarks: ["Table Mountain", "Kruger National Park", "Robben Island", "Cape of Good Hope", "Apartheid Museum"],
    neighbors: ["Namibia", "Botswana", "Zimbabwe", "Mozambique", "Eswatini", "Lesotho"],
    languages: ["English", "Afrikaans", "Zulu", "Xhosa"],
    currency: "South African Rand (ZAR)",
    area: 1221037,
    landlocked: false,
    independenceYear: 1910,
    unescoSites: ["Robben Island", "Fossil Hominid Sites"],
    famousExports: ["Gold", "Diamonds", "Platinum", "Wine"],
    shape: "south-africa"
  },
  {
    id: 17,
    name: "Egypt",
    capital: "Cairo",
    population: 102300000,
    continent: "Africa",
    region: "Northern Africa",
    flag: "🇪🇬",
    majorCities: ["Cairo", "Alexandria", "Giza", "Luxor", "Aswan"],
    landmarks: ["Pyramids of Giza", "Sphinx", "Luxor Temple", "Abu Simbel", "Valley of the Kings"],
    neighbors: ["Libya", "Sudan", "Israel"],
    languages: ["Arabic"],
    currency: "Egyptian Pound (EGP)",
    area: 1002450,
    landlocked: false,
    independenceYear: 1922,
    unescoSites: ["Memphis and its Necropolis", "Ancient Thebes", "Abu Simbel"],
    famousExports: ["Petroleum", "Natural Gas", "Cotton", "Textiles"],
    shape: "egypt"
  },
  {
    id: 18,
    name: "Nigeria",
    capital: "Abuja",
    population: 206100000,
    continent: "Africa",
    region: "Western Africa",
    flag: "🇳🇬",
    majorCities: ["Lagos", "Abuja", "Kano", "Ibadan", "Port Harcourt"],
    landmarks: ["Zuma Rock", "Yankari National Park", "Olumo Rock", "Lekki Conservation Centre"],
    neighbors: ["Benin", "Niger", "Chad", "Cameroon"],
    languages: ["English", "Hausa", "Yoruba", "Igbo"],
    currency: "Nigerian Naira (NGN)",
    area: 923768,
    landlocked: false,
    independenceYear: 1960,
    unescoSites: ["Sukur Cultural Landscape", "Osun-Osogbo Sacred Grove"],
    famousExports: ["Petroleum", "Natural Gas", "Cocoa", "Rubber"],
    shape: "nigeria"
  },
  {
    id: 19,
    name: "Kenya",
    capital: "Nairobi",
    population: 53800000,
    continent: "Africa",
    region: "Eastern Africa",
    flag: "🇰🇪",
    majorCities: ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret"],
    landmarks: ["Maasai Mara", "Mount Kenya", "Amboseli National Park", "Lake Nakuru", "Lamu Old Town"],
    neighbors: ["Ethiopia", "Somalia", "South Sudan", "Tanzania", "Uganda"],
    languages: ["English", "Swahili"],
    currency: "Kenyan Shilling (KES)",
    area: 580367,
    landlocked: false,
    independenceYear: 1963,
    unescoSites: ["Mount Kenya National Park", "Lamu Old Town", "Sacred Mijikenda Kaya Forests"],
    famousExports: ["Tea", "Coffee", "Flowers", "Tourism"],
    shape: "kenya"
  },
  {
    id: 20,
    name: "Turkey",
    capital: "Ankara",
    population: 84300000,
    continent: "Asia",
    region: "Western Asia",
    flag: "🇹🇷",
    majorCities: ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya"],
    landmarks: ["Hagia Sophia", "Blue Mosque", "Cappadocia", "Ephesus", "Pamukkale"],
    neighbors: ["Greece", "Bulgaria", "Georgia", "Armenia", "Azerbaijan", "Iran", "Iraq", "Syria"],
    languages: ["Turkish"],
    currency: "Turkish Lira (TRY)",
    area: 783562,
    landlocked: false,
    independenceYear: 1923,
    unescoSites: ["Historic Areas of Istanbul", "Göreme National Park", "Ephesus"],
    famousExports: ["Textiles", "Automobiles", "Electronics", "Dried Fruits"],
    shape: "turkey"
  },
  {
    id: 21,
    name: "South Korea",
    capital: "Seoul",
    population: 51300000,
    continent: "Asia",
    region: "Eastern Asia",
    flag: "🇰🇷",
    majorCities: ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon"],
    landmarks: ["Gyeongbokgung Palace", "N Seoul Tower", "DMZ", "Bulguksa Temple", "Jeju Island"],
    neighbors: ["North Korea"],
    languages: ["Korean"],
    currency: "South Korean Won (KRW)",
    area: 100210,
    landlocked: false,
    independenceYear: 1948,
    unescoSites: ["Changdeokgung Palace", "Jeju Volcanic Island", "Seokguram Grotto"],
    famousExports: ["Electronics", "Automobiles", "Ships", "K-pop"],
    shape: "south-korea"
  },
  {
    id: 22,
    name: "Thailand",
    capital: "Bangkok",
    population: 69800000,
    continent: "Asia",
    region: "South-Eastern Asia",
    flag: "🇹🇭",
    majorCities: ["Bangkok", "Chiang Mai", "Pattaya", "Phuket", "Ayutthaya"],
    landmarks: ["Grand Palace", "Wat Arun", "Phi Phi Islands", "Ayutthaya Historical Park", "Big Buddha"],
    neighbors: ["Myanmar", "Laos", "Cambodia", "Malaysia"],
    languages: ["Thai"],
    currency: "Thai Baht (THB)",
    area: 513120,
    landlocked: false,
    independenceYear: null,
    unescoSites: ["Historic City of Ayutthaya", "Historic Town of Sukhothai"],
    famousExports: ["Rice", "Rubber", "Electronics", "Automobiles"],
    shape: "thailand"
  },
  {
    id: 23,
    name: "Poland",
    capital: "Warsaw",
    population: 37900000,
    continent: "Europe",
    region: "Eastern Europe",
    flag: "🇵🇱",
    majorCities: ["Warsaw", "Krakow", "Lodz", "Wroclaw", "Poznan"],
    landmarks: ["Wawel Castle", "Auschwitz", "Old Town Warsaw", "Wieliczka Salt Mine", "Malbork Castle"],
    neighbors: ["Germany", "Czech Republic", "Slovakia", "Ukraine", "Belarus", "Lithuania", "Russia"],
    languages: ["Polish"],
    currency: "Polish Zloty (PLN)",
    area: 312696,
    landlocked: false,
    independenceYear: 1918,
    unescoSites: ["Historic Centre of Krakow", "Auschwitz Birkenau", "Wieliczka Salt Mine"],
    famousExports: ["Machinery", "Furniture", "Food Products", "Automotive Parts"],
    shape: "poland"
  },
  {
    id: 24,
    name: "Netherlands",
    capital: "Amsterdam",
    population: 17400000,
    continent: "Europe",
    region: "Western Europe",
    flag: "🇳🇱",
    majorCities: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven"],
    landmarks: ["Windmills", "Rijksmuseum", "Anne Frank House", "Keukenhof Gardens", "Canals of Amsterdam"],
    neighbors: ["Belgium", "Germany"],
    languages: ["Dutch"],
    currency: "Euro (EUR)",
    area: 41850,
    landlocked: false,
    independenceYear: 1581,
    unescoSites: ["Seventeenth-century canal ring area of Amsterdam", "Van Nellefabriek"],
    famousExports: ["Flowers", "Cheese", "Electronics", "Chemicals"],
    shape: "netherlands"
  },
  {
    id: 25,
    name: "Switzerland",
    capital: "Bern",
    population: 8700000,
    continent: "Europe",
    region: "Western Europe",
    flag: "🇨🇭",
    majorCities: ["Zurich", "Geneva", "Basel", "Bern", "Lausanne"],
    landmarks: ["Matterhorn", "Jungfrau", "Lake Geneva", "Rhine Falls", "Chapel Bridge"],
    neighbors: ["France", "Germany", "Austria", "Liechtenstein", "Italy"],
    languages: ["German", "French", "Italian", "Romansh"],
    currency: "Swiss Franc (CHF)",
    area: 41285,
    landlocked: true,
    independenceYear: 1291,
    unescoSites: ["Old City of Bern", "Swiss Alps Jungfrau-Aletsch"],
    famousExports: ["Watches", "Chocolate", "Pharmaceuticals", "Banking Services"],
    shape: "switzerland"
  },
  {
    id: 26,
    name: "Sweden",
    capital: "Stockholm",
    population: 10400000,
    continent: "Europe",
    region: "Northern Europe",
    flag: "🇸🇪",
    majorCities: ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Västerås"],
    landmarks: ["Vasa Museum", "Drottningholm Palace", "Ice Hotel", "Abisko National Park", "Stockholm Archipelago"],
    neighbors: ["Norway", "Finland"],
    languages: ["Swedish"],
    currency: "Swedish Krona (SEK)",
    area: 450295,
    landlocked: false,
    independenceYear: null,
    unescoSites: ["Drottningholm Palace", "Birka and Hovgården"],
    famousExports: ["Iron Ore", "Machinery", "Automobiles", "Paper Products"],
    shape: "sweden"
  },
  {
    id: 27,
    name: "Norway",
    capital: "Oslo",
    population: 5400000,
    continent: "Europe",
    region: "Northern Europe",
    flag: "🇳🇴",
    majorCities: ["Oslo", "Bergen", "Trondheim", "Stavanger", "Tromsø"],
    landmarks: ["Fjords", "Northern Lights", "Viking Ship Museum", "Preikestolen", "Geirangerfjord"],
    neighbors: ["Sweden", "Finland", "Russia"],
    languages: ["Norwegian"],
    currency: "Norwegian Krone (NOK)",
    area: 385207,
    landlocked: false,
    independenceYear: 1905,
    unescoSites: ["Bryggen", "West Norwegian Fjords"],
    famousExports: ["Oil", "Natural Gas", "Fish", "Aluminum"],
    shape: "norway"
  },
  {
    id: 28,
    name: "Greece",
    capital: "Athens",
    population: 10400000,
    continent: "Europe",
    region: "Southern Europe",
    flag: "🇬🇷",
    majorCities: ["Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa"],
    landmarks: ["Acropolis", "Parthenon", "Santorini", "Delphi", "Meteora"],
    neighbors: ["Albania", "North Macedonia", "Bulgaria", "Turkey"],
    languages: ["Greek"],
    currency: "Euro (EUR)",
    area: 131957,
    landlocked: false,
    independenceYear: 1821,
    unescoSites: ["Acropolis of Athens", "Archaeological Site of Delphi", "Meteora"],
    famousExports: ["Olive Oil", "Tourism", "Shipping Services", "Citrus Fruits"],
    shape: "greece"
  },
  {
    id: 29,
    name: "Portugal",
    capital: "Lisbon",
    population: 10200000,
    continent: "Europe",
    region: "Southern Europe",
    flag: "🇵🇹",
    majorCities: ["Lisbon", "Porto", "Braga", "Coimbra", "Faro"],
    landmarks: ["Belém Tower", "Jerónimos Monastery", "Pena Palace", "Porto Wine Cellars", "Cliffs of Cabo da Roca"],
    neighbors: ["Spain"],
    languages: ["Portuguese"],
    currency: "Euro (EUR)",
    area: 92090,
    landlocked: false,
    independenceYear: 1143,
    unescoSites: ["Monastery of Jerónimos", "Tower of Belém", "Historic Centre of Porto"],
    famousExports: ["Wine", "Cork", "Textiles", "Footwear"],
    shape: "portugal"
  },
  {
    id: 30,
    name: "New Zealand",
    capital: "Wellington",
    population: 5100000,
    continent: "Oceania",
    region: "Australia and New Zealand",
    flag: "🇳🇿",
    majorCities: ["Auckland", "Wellington", "Christchurch", "Hamilton", "Dunedin"],
    landmarks: ["Milford Sound", "Mount Cook", "Hobbiton", "Sky Tower", "Franz Josef Glacier"],
    neighbors: [],
    languages: ["English", "Māori"],
    currency: "New Zealand Dollar (NZD)",
    area: 268838,
    landlocked: false,
    independenceYear: 1907,
    unescoSites: ["Tongariro National Park", "Te Wahipounamu"],
    famousExports: ["Dairy Products", "Meat", "Wine", "Wool"],
    shape: "new-zealand"
  }
];
